/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/old_tv/scene.gltf -o src/components/OldTv.jsx 
Author: visualdiscette (https://sketchfab.com/visualdiscette)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-tv-3fb1a4b9d14c44abaac69fec119bf251
Title: Old TV
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function OldTv(props) {
  const { nodes, materials } = useGLTF('/old_tv/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.TV_buttonWhite_0.geometry} material={materials.buttonWhite} />
        <mesh geometry={nodes.TV_Buttons_0.geometry} material={materials.Buttons} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.TV009_baseBack_0.geometry} material={materials.baseBack} />
        <mesh geometry={nodes.TV009_Metal_0.geometry} material={materials.Metal} />
      </group>
      <mesh geometry={nodes.TV001_Base_0.geometry} material={materials.Base} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.TV002_Base_0.geometry} material={materials.Base} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.TV003_Glass_0.geometry} material={materials.Glass} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.TV004_baseBack_0.geometry} material={materials.baseBack} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.TV005_Base_0.geometry} material={materials.Base} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.TV006_baseBack_0.geometry} material={materials.baseBack} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.TV007_baseBack_0.geometry} material={materials.baseBack} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.TV008_baseBack_0.geometry} material={materials.baseBack} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.TV011_glassBack_0.geometry} material={materials.glassBack} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.BezierCurve_Wire_0.geometry} material={materials.Wire} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/old_tv/scene.gltf')
